new logic for mysql and postgres checks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2478,6 +2478,8 @@ case $host_os in *\ *) host_os=`echo "$host_os" | sed 's/ /-/g'`;; esac
 # Check whether --with-mysql was given.
 if test "${with_mysql+set}" = set; then
   withval=$with_mysql;
+else
+  with_mysql=check
 fi
 
 
@@ -2485,6 +2487,8 @@ fi
 # Check whether --with-pgsql was given.
 if test "${with_pgsql+set}" = set; then
   withval=$with_pgsql;
+else
+  with_pgsql=check
 fi
 
 
@@ -5572,7 +5576,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5575 "configure"' > conftest.$ac_ext
+  echo '#line 5579 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6134,7 +6138,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6137: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6141: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7354,7 +7358,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 7357 "configure"' > conftest.$ac_ext
+    echo '#line 7361 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8086,7 +8090,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8089 "configure"
+#line 8093 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8184,7 +8188,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8187 "configure"
+#line 8191 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10859,31 +10863,154 @@ _ACEOF
 
 { echo "$as_me:$LINENO: checking pgsql" >&5
 echo $ECHO_N "checking pgsql... $ECHO_C" >&6; }
-if test "x$with_pgsql" != "xyes"; then
-  PGSQL_DIR=$with_pgsql
+if test "x$with_pgsql" != "xno"; then
+  if test "x$with_pgsql" != "xcheck"; then
+        PGSQL_DIR=$with_pgsql
+    else
+                for i in /usr /usr/local /usr/local/psql; do
+            test -f $i/bin/psql && PGSQL_DIR=$i && break
+        done
+    fi
+
+    if test -n $PGSQL_DIR; then
+        OLD_CPPFLAGS=$CPPFLAGS
+        for i in include/postgresql include; do
+            if test -d ${PGSQL_DIR}/$i; then
+                PGSQL_INC_DIR=$i
+                break
+            fi
+        done
+        CPPFLAGS="$CPPFLAGS -I${PGSQL_DIR}/${PGSQL_INC_DIR}"
+        if test "${ac_cv_header_libpq_fe_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for libpq-fe.h" >&5
+echo $ECHO_N "checking for libpq-fe.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_libpq_fe_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_libpq_fe_h" >&5
+echo "${ECHO_T}$ac_cv_header_libpq_fe_h" >&6; }
 else
-  for i in /usr /usr/local /usr/local/psql; do
-    test -f $i/bin/psql                         && PGSQL_DIR=$i
-  done
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking libpq-fe.h usability" >&5
+echo $ECHO_N "checking libpq-fe.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <libpq-fe.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
 fi
 
-for i in $PGSQL_DIR /usr /usr/local /usr/local/pgsql; do
-   test -f $i/include/libpq-fe.h                    && PGSQL_INC_DIR=$i/include
-   test -f $i/include/postgresql/libpq-fe.h         && PGSQL_INC_DIR=$i/include/postgresql
-done
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
 
-if test -z "$PGSQL_INC_DIR"; then
-  if test "x$with_pgsql" != "x"; then
-    { { echo "$as_me:$LINENO: error: Cannot find Postgres header files under $PGSQL_DIR" >&5
-echo "$as_me: error: Cannot find Postgres header files under $PGSQL_DIR" >&2;}
-   { (exit 1); exit 1; }; }
-  else
-    { echo "$as_me:$LINENO: WARNING: Cannot find Postgres headers.  Use --with-pgsql= to specify non-default path." >&5
-echo "$as_me: WARNING: Cannot find Postgres headers.  Use --with-pgsql= to specify non-default path." >&2;}
-  fi
+# Is the header present?
+{ echo "$as_me:$LINENO: checking libpq-fe.h presence" >&5
+echo $ECHO_N "checking libpq-fe.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libpq-fe.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
 fi
 
-{ echo "$as_me:$LINENO: checking for PQconnectdb in -lpq" >&5
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: libpq-fe.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: libpq-fe.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: libpq-fe.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: libpq-fe.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: libpq-fe.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: libpq-fe.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libpq-fe.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libpq-fe.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: libpq-fe.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for libpq-fe.h" >&5
+echo $ECHO_N "checking for libpq-fe.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_libpq_fe_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_libpq_fe_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_libpq_fe_h" >&5
+echo "${ECHO_T}$ac_cv_header_libpq_fe_h" >&6; }
+
+fi
+if test $ac_cv_header_libpq_fe_h = yes; then
+   CPPFLAGS=$OLD_CPPFLAGS
+            OLD_LDFLAGS=$LDFLAGS
+            LDFLAGS="$LDFLAGS -lpq"
+            { echo "$as_me:$LINENO: checking for PQconnectdb in -lpq" >&5
 echo $ECHO_N "checking for PQconnectdb in -lpq... $ECHO_C" >&6; }
 if test "${ac_cv_lib_pq_PQconnectdb+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10945,47 +11072,190 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_pq_PQconnectdb" >&5
 echo "${ECHO_T}$ac_cv_lib_pq_PQconnectdb" >&6; }
 if test $ac_cv_lib_pq_PQconnectdb = yes; then
-   PGSQL_LIB="-lpq"
+   LDFLAGS=$OLD_LDFLAGS
+                PGSQL_LIB="-lpq"
 
-       PGSQL_CPPFLAGS="-I${PGSQL_INC_DIR}"
+                PGSQL_CPPFLAGS="-I${PGSQL_DIR}/${PGSQL_INC_DIR}"
 
-       ltlibraries="libratedpgsql.la $ltlibraries"
+                ltlibraries="libratedpgsql.la $ltlibraries"
 else
-  { echo "$as_me:$LINENO: WARNING: Cannot link with Postgres libs! (libpq)" >&5
+   LDFLAGS=$OLD_LDFLAGS
+                if test "x$with_pgsql" != "xcheck"; then
+                    { { echo "$as_me:$LINENO: error: Cannot link with Postgres libs! (libpq)" >&5
+echo "$as_me: error: Cannot link with Postgres libs! (libpq)" >&2;}
+   { (exit 1); exit 1; }; }
+                else
+                    { echo "$as_me:$LINENO: WARNING: Cannot link with Postgres libs! (libpq)" >&5
 echo "$as_me: WARNING: Cannot link with Postgres libs! (libpq)" >&2;}
+                fi
+fi
+
+else
+   CPPFLAGS=$OLD_CPPFLAGS
+            if test "x$with_pgsql" != "xcheck"; then
+                { { echo "$as_me:$LINENO: error: \"Cannot find Postgres headers in ${PGSQL_DIR}\"" >&5
+echo "$as_me: error: \"Cannot find Postgres headers in ${PGSQL_DIR}\"" >&2;}
+   { (exit 1); exit 1; }; }
+            else
+                { echo "$as_me:$LINENO: WARNING: \"Cannot find Postgres headers in ${PGSQL_DIR}. Use --with-pgsql to specify non-default path.\"" >&5
+echo "$as_me: WARNING: \"Cannot find Postgres headers in ${PGSQL_DIR}. Use --with-pgsql to specify non-default path.\"" >&2;}
+            fi
+fi
+
+
+    fi
+
+
 fi
 
 
 
 { echo "$as_me:$LINENO: checking mysql" >&5
 echo $ECHO_N "checking mysql... $ECHO_C" >&6; }
+if test "x$with_mysql" != "xno"; then
+  if test "x$with_mysql" != "xcheck"; then
+        MYSQL_DIR=$with_mysql
+    else
+                for i in /usr /usr/local /usr/local/mysql; do
+            test -f $i/bin/mysql_config && MYSQL_DIR=$i && break
+        done
+    fi
 
-if test "x$with_mysql" != "xyes"; then
-  MYSQL_DIR=$with_mysql
+    if test -n $MYSQL_DIR -a -x ${MYSQL_DIR}/bin/mysql_config; then
+        MYSQL_CPPFLAGS=`${MYSQL_DIR}/bin/mysql_config --include`
+        OLD_CPPFLAGS=$CPPFLAGS
+        CPPFLAGS="$CPPFLAGS $MYSQL_CPPFLAGS"
+        if test "${ac_cv_header_mysql_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for mysql.h" >&5
+echo $ECHO_N "checking for mysql.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_mysql_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_mysql_h" >&5
+echo "${ECHO_T}$ac_cv_header_mysql_h" >&6; }
 else
-  for i in /usr /usr/local /usr/local/mysql; do
-    test -f $i/bin/mysql                         && MYSQL_DIR=$i
-  done
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking mysql.h usability" >&5
+echo $ECHO_N "checking mysql.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <mysql.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
 fi
 
-for i in $MYSQL_DIR /usr /usr/local /usr/local/mysql; do
-   test -f $i/include/mysql.h                    && MYSQL_INC_DIR=$i/include
-   test -f $i/include/mysql/mysql.h              && MYSQL_INC_DIR=$i/include/mysql
-   test -f $i/mysql/include/mysql.h              && MYSQL_INC_DIR=$i/mysql/include
-done
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
 
-if test -z "$MYSQL_INC_DIR"; then
-  if test "x$with_mysql" != "x"; then
-    { { echo "$as_me:$LINENO: error: Cannot find MySQL header files under $MYSQL_DIR" >&5
-echo "$as_me: error: Cannot find MySQL header files under $MYSQL_DIR" >&2;}
-   { (exit 1); exit 1; }; }
-  else
-    { echo "$as_me:$LINENO: WARNING: Cannot find MySQL headers.  Use --with-mysql= to specify non-default path." >&5
-echo "$as_me: WARNING: Cannot find MySQL headers.  Use --with-mysql= to specify non-default path." >&2;}
-  fi
+# Is the header present?
+{ echo "$as_me:$LINENO: checking mysql.h presence" >&5
+echo $ECHO_N "checking mysql.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <mysql.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
 fi
 
-{ echo "$as_me:$LINENO: checking for my_thread_init in -lmysqlclient_r" >&5
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: mysql.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: mysql.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: mysql.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: mysql.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: mysql.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: mysql.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: mysql.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: mysql.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mysql.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mysql.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: mysql.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for mysql.h" >&5
+echo $ECHO_N "checking for mysql.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_mysql_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_mysql_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_mysql_h" >&5
+echo "${ECHO_T}$ac_cv_header_mysql_h" >&6; }
+
+fi
+if test $ac_cv_header_mysql_h = yes; then
+   CPPFLAGS=$OLD_CPPFLAGS
+            MYSQL_LIB=`${MYSQL_DIR}/bin/mysql_config --libs_r`
+            OLD_LDFLAGS=$LDFLAGS
+            LDFLAGS="$LDFLAGS $MYSQL_LIB"
+            { echo "$as_me:$LINENO: checking for my_thread_init in -lmysqlclient_r" >&5
 echo $ECHO_N "checking for my_thread_init in -lmysqlclient_r... $ECHO_C" >&6; }
 if test "${ac_cv_lib_mysqlclient_r_my_thread_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11047,14 +11317,38 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_my_thread_init" >&5
 echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_my_thread_init" >&6; }
 if test $ac_cv_lib_mysqlclient_r_my_thread_init = yes; then
-   MYSQL_LIB="-lmysqlclient_r"
+   LDFLAGS=$OLD_LDFLAGS
 
-       MYSQL_CPPFLAGS="-I${MYSQL_INC_DIR}"
 
-       ltlibraries="libratedmysql.la $ltlibraries"
+                ltlibraries="libratedmysql.la $ltlibraries"
 else
-  { echo "$as_me:$LINENO: WARNING: Cannot link with thread-safe MySQL lib (libmysqlclient_r)" >&5
+   LDFLAGS=$OLD_LDFLAGS
+                if test "x$with_mysql" != "xcheck"; then
+                    { { echo "$as_me:$LINENO: error: Cannot link with thread-safe MySQL lib (libmysqlclient_r)" >&5
+echo "$as_me: error: Cannot link with thread-safe MySQL lib (libmysqlclient_r)" >&2;}
+   { (exit 1); exit 1; }; }
+                else
+                    { echo "$as_me:$LINENO: WARNING: Cannot link with thread-safe MySQL lib (libmysqlclient_r)" >&5
 echo "$as_me: WARNING: Cannot link with thread-safe MySQL lib (libmysqlclient_r)" >&2;}
+                fi
+fi
+
+else
+   CPPFLAGS=$OLD_CPPFLAGS
+            if test "x$with_mysql" != "xcheck"; then
+                { { echo "$as_me:$LINENO: error: \"Cannot find MySQL headers in ${MYSQL_CPPFLAGS}\"" >&5
+echo "$as_me: error: \"Cannot find MySQL headers in ${MYSQL_CPPFLAGS}\"" >&2;}
+   { (exit 1); exit 1; }; }
+            else
+                { echo "$as_me:$LINENO: WARNING: \"Cannot find MySQL headers in ${MYSQL_CPPFLAGS}.  Use --with-mysql= to specify non-default path.\"" >&5
+echo "$as_me: WARNING: \"Cannot find MySQL headers in ${MYSQL_CPPFLAGS}.  Use --with-mysql= to specify non-default path.\"" >&2;}
+            fi
+fi
+
+
+    fi
+
+
 fi
 
 
